# Generated by Django 5.0.7 on 2024-08-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_remove_restaurant_data_menuitem_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="restaurant",
            unique_together={("name", "address")},
        ),
    ]
